# Chrome storage data key
DATA_KEY = 'game-of-spoils'

# jQuery selectors that specify elements to block on each supported site
AVCLUB_FEED_ELEMENTS_SELECTOR      = '.item, article.short, article > .heading'
BUZZFEED_ELEMENTS_SELECTOR         = '.lede'
FACEBOOK_FEED_ELEMENTS_SELECTOR    = '.fbUserContent, #pagelet_trending_tags_and_topics ul > li'
FEEDLY_ELEMENTS_SELECTOR           = '.u5Entry > div, .u0Entry, .topRecommendedEntry, .u4Entry > div, .u100Frame, .u12Entry > div'
GIZMODO_ELEMENTS_SELECTOR          = '.featured-item, article'
GOOGLE_NEWS_FEED_ELEMENTS_SELECTOR = '.blended-wrapper'
GOOGLE_PLUS_ELEMENTS_SELECTOR      = 'div[id^="update-"], c-wiz div div c-wiz'
REDDIT_FEED_ELEMENTS_SELECTOR      = '.sitetable > .thing.link:visible'
SLACK_FEED_ELEMENTS_SELECTOR       = 'ts-message'
TUMBLR_ELEMENTS_SELECTOR           = '.post_container, article'
TWITTER_FEED_ELEMENTS_SELECTOR     = "[data-item-type='tweet'], .trend-item"
YOUTUBE_ELEMENTS_SELECTOR          = '.yt-lockup, .related-list-item, .comment-renderer-text'

# GoT-specific words that are potentially spoiler-ific and thus trigger a spoiler blocker
SPOILER_WORDS_LIST = [
  '#got'
  'ady stonehea'
  'aidan gillen'
  'alfie allen'
  'arya stark'
  'asoiaf'
  'azor ahai'
  'baelish'
  'baratheon'
  'ben crompton'
  'bloodraven'
  'braavos'
  'bran stark'
  'briene of tarth'
  'brienne of tarth'
  'carice van houten'
  'casterly rock'
  'cersei '
  'conleth hill'
  'd.b. weiss'
  'daenerys'
  'daniel portman'
  'david benioff'
  'davos seaworth'
  'dornish'
  'dothraki'
  'dreadfort'
  'emilia clarke'
  'game of thrones'
  'gameofthrone'
  'greyjoy'
  'gwendoline christie'
  'highgarden'
  'hodor'
  'house bolton'
  'house stark'
  'house tyrell'
  'howland reed'
  'iain glen'
  'ian mcelhinney'
  'iron throne'
  'isaac hempstead wright'
  'jerome flynn'
  'john bradley'
  'jojen reed'
  'jon snow'
  'julian glover'
  'khaleesi'
  "king's landing"
  'kit harington'
  'kit harrington'
  'kristian nairn'
  'lanister'
  'lannisport'
  'lannister'
  'lena headey'
  'liam cunningham'
  'littlefinger'
  'maisie williams'
  'meereen'
  'melisandre'
  'michele fairley'
  'michelle fairley'
  'myrcella'
  'natalie dormer'
  'nathalie emmanue'
  'ned stark'
  'nikolaj coster-waldau'
  'olenna tyrell'
  'peter dinklage'
  'podrick payne'
  'queen of thorns'
  'ramsay bolton'
  'roose bolton'
  'rory mccann'
  'sandor clegane'
  'sansa stark'
  'sophie turner'
  'sothoryos'
  'stephen dillane'
  'targaryen'
  'tower of joy'
  'tyrion'
  'vaes dothrak'
  'viserys'
  'walder frey'
  'westeros'
  'white walker'
  'whitewalker'
  'wildling'
  'winterfell'
]

# Regex formed from the spoiler array for quick matching
SPOILER_WORDS_REGEX = new RegExp(SPOILER_WORDS_LIST.join('|'), 'i')


# Phrases to describe the grisly ways that spoilers are disposed of
DEATH_NAMES = [
  "got burned at the stake to appease R'hllor"
  'contracted greyscale and was quarantined permanently'
  'did not live through the Long Night'
  'drank way too much Moon Tea'
  'found itself too far north when winter came'
  'is dark and full of terrors'
  'lost in trial by combat'
  'did not win the game of thrones'
  'suffered terribly at the paws of Ser Pounce'
  'warged into a dead cat'
  'was grimly beheaded for desertion'
  'was impaled by a lance at a tournament by a lowly hedge knight'
  'was incinerated by hot dragon breath'
  'was murdered by its very own nuncle'
  'was slain by a shadow'
  'was slowly poisoned over a period of many fortnights'
  'was torn asunder by six direwolves'
]

# Subreddits that are GoT related, dont block GoT-related things there, since that'd pretty much block everything...
GOT_RELATED_SUBREDDITS = [
  'gameofthrones'
  'asoiaf'
  'iceandfire'
  'agotboardgame'
  'gamesofthrones'
  'westeros'
  'thronescomics'
  'asongofmemesandrage'
  'earthoficeandfire'
]
GOT_SUBREDDITS_REGEX = new RegExp('(\/r\/)' + GOT_RELATED_SUBREDDITS.join('|'), 'i')
